# Generated by Django 5.0.6 on 2024-05-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texhort', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='downvote',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='upvote',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
